# Generated by Django 4.2.3 on 2023-07-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_gender_product_is_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Accesorios', 'Accesorios'), ('Deporte', 'Deporte'), ('Zapatos', 'Zapatos'), ('RopaInterior', 'RopaInterior'), ('RopaBaño', 'RopaBaño'), ('Camisa', 'Camisa'), ('Pantalones', 'Pantalones'), ('Chaquetas', 'Chaquetas'), ('ZapatosVestir', 'ZapatosVestir'), ('Trajes', 'Trajes'), ('Jeans', 'Jeans'), ('Polos', 'Polos'), ('Bolsos', 'Bolsos'), ('Vestidos', 'Vestidos'), ('Faldas', 'Faldas'), ('Blusas', 'Blusas'), ('ZapatosTacon', 'ZapatosTacon'), ('Pijamas', 'Pijamas'), ('Playeras', 'Playeras')], default='Ropa', max_length=20),
        ),
    ]
